spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///D:/BACKUP/Music/4.config-data-copy
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000